before_install:
  - echo 'Set exec bit on cibuild script'
  - chmod a+x ./scripts/cibuild
  - echo 'Run gem install bundler'
  - gem install bundler
  - echo 'No need to run npm install or install webpack'
  - echo 'Set bundle deployment flag'
  - bundle config set deployment 'true'

git:
  depth: 1

script: ./scripts/cibuild

deploy:
  provider: pages
  local_dir: _site
  target_branch: master
  skip_cleanup: true
  github_token: $GH_TOKEN
  on:
    branch: source

cache: bundler

notifications:
  email: 
    on_success: never
    on_failure: always
